name: publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -q pipenv
        make install
    - name: Build
      run: |
        make compile
        make build
    - name: Test
      run: |
        make test
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pipenv run twine upload dist/*
